version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: mongo:4.4.4
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            make test
      - store_test_results:
          path: reports

workflows:
  default:
    jobs:
      - build